apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::439307002497:role/eksctl-expense-nodegroup-expense-NodeInstanceRole-bHBekHgZ8GNi
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2025-08-10T02:26:51Z"
  name: aws-auth
  namespace: kube-system
  uid: 6d3b7de2-aa2e-4c81-9bdb-67c19a9ba012

